## Exercise 6 - Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have 30 integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(10,40)
arr2 = np.arange(220,250)

result_array = np.add(arr1, arr2)
print("Added array:", result_array)

Added array: [230 232 234 236 238 240 242 244 246 248 250 252 254 256 258 260 262 264
 266 268 270 272 274 276 278 280 282 284 286 288]


2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [4]:
n = 100 + 10 * 7

new_arr = np.arange(100,n).reshape(10,7)
new_arr

array([[100, 101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168, 169]])

3 Generate three-dimensional array (3x3x3) with random floats.

In [5]:
arr3 = np.random.rand(3,3,3)

arr3

array([[[0.38103355, 0.86674568, 0.5272139 ],
        [0.46732404, 0.94322805, 0.88639135],
        [0.36180772, 0.64015266, 0.61082495]],

       [[0.78418715, 0.92123187, 0.9672456 ],
        [0.15063587, 0.0068579 , 0.68083348],
        [0.07497425, 0.48038344, 0.88492713]],

       [[0.14222754, 0.15482887, 0.60810343],
        [0.39224004, 0.81804938, 0.57116741],
        [0.67926766, 0.51456278, 0.02414989]]])

4 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each corresponding numbers from these two arrays for the result array.

In [12]:
arr4 = np.arange(1,50,2)
arr5 = np.arange(2,51,2)

multiply_arrays = arr4 * arr5

multiply_arrays

array([   2,   12,   30,   56,   90,  132,  182,  240,  306,  380,  462,
        552,  650,  756,  870,  992, 1122, 1260, 1406, 1560, 1722, 1892,
       2070, 2256, 2450])

5 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 6 are presented.

In [13]:
arr6 = np.random.randint(1000, size=(40,5))

arr6

array([[602, 626, 255, 856, 246],
       [773,  54, 945, 357, 153],
       [757, 823, 474,  14, 102],
       [903, 421, 813, 330, 170],
       [644, 455,   0,  79, 230],
       [895, 741, 146, 765, 800],
       [393, 614, 764, 161, 113],
       [914, 908, 746, 731, 920],
       [309, 122, 705, 860,  97],
       [763, 820, 213, 380, 813],
       [492, 536, 127, 984, 620],
       [178, 448, 229,  75, 760],
       [894, 914, 920,   6, 444],
       [410,  56, 619, 704, 130],
       [ 23, 857, 224, 882, 809],
       [612,  44, 859,  62, 921],
       [715, 844, 569, 600, 421],
       [531, 255, 147, 499, 326],
       [433, 567,  17, 924, 414],
       [385, 683, 437, 779, 601],
       [441, 379, 959, 929, 647],
       [154, 114, 656, 699, 207],
       [168, 177,  64, 633,  43],
       [477, 672, 309, 516,  25],
       [373, 151, 270, 113, 693],
       [ 29, 756, 944, 532, 973],
       [812, 155, 705, 364, 363],
       [568, 634,  38, 665, 592],
       [389, 787, 435, 718, 445],
       [756, 4